In [2]:
import numpy as np

In [4]:
data1 = [6, 7.5, 8, 0, 1]

In [5]:
array1 = np.array(data1)

In [6]:
array1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7 ,8]]

In [8]:
array2 = np.array(data2)

In [9]:
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
array2.ndim

2

In [11]:
array1.ndim

1

In [12]:
array2.shape

(2, 4)

In [13]:
array2.dtype

dtype('int32')

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.empty((3,3,2))

array([[[1.14156408e+243, 2.57609093e+257],
        [3.03665435e-152, 9.08367206e+223],
        [1.14448785e+243, 6.11262471e-154]],

       [[5.29862103e+180, 9.08367206e+223],
        [7.14658370e+159, 1.10639950e+200],
        [5.22878778e+257, 6.19633416e+223]],

       [[1.72403947e+272, 6.01347153e-154],
        [4.88573032e+252, 9.30916287e+199],
        [2.64521559e+185, 2.59345432e+161]]])

In [19]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [20]:
arr = np.array([1,2,3,4,5])

In [21]:
arr.dtype

dtype('int32')

In [24]:
arr.astype(float)

array([1., 2., 3., 4., 5.])

In [23]:
arr.dtype

dtype('int32')

astype는 자료형을 변경하여 보여주는 것이고, 그 자료의 자료형이 바뀌는 것이 아니므로 float 자료형으로 바꾼 arr를 사용하려면 또 다른 변수에 지정을 해주어야 한다.

In [25]:
float_arr = arr.astype(float)

In [26]:
float_arr

array([1., 2., 3., 4., 5.])

In [27]:
float_arr.dtype

dtype('float64')

In [28]:
arr2=np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [29]:
arr2.astype(int)

array([ 3, -1, -2,  0, 12, 10])

float 자료형을 int 자료형으로 바꾸어주면 내림하여 정수를 받음!!

In [30]:
int_array = np.arange(5)

In [31]:
int_array

array([0, 1, 2, 3, 4])

In [32]:
float_array = np.array([1.2,3.6])

In [33]:
int_array.astype(float_array.dtype)

array([0., 1., 2., 3., 4.])

int_array의 정수형 자료의 값을 float_array의 실수형 자료의 값으로 모두 바꿀 수 있음!

In [34]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [35]:
arr^2

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [39]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

array의 연산은 각 위치에 맞는 원소끼리 연산한다!

★★ slicing -> array의 slice는 view이다. 즉 slicing한 후 slicing된 자료의 자료를 변경하면 원자료의 자료까지 변경된다

In [40]:
arr = np.arange(10)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[5:8]=10

arr의 인덱스 5번부터 7번까지에 해당하는 자료를 10으로 바꾸어준다.

In [43]:
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [44]:
arr_slice = arr[5:8]

In [45]:
arr_slice

array([10, 10, 10])

In [46]:
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [49]:
arr_slice[0:2]=64

In [50]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 10,  8,  9])

In [51]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [53]:
arr2d[2]

array([7, 8, 9])

In [54]:
arr2d[0, 1]

2

In [55]:
arr2d[0][1]

2

In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [57]:
old_values = arr3d[0].copy() #자료 복사

In [58]:
arr3d[0]=42

In [59]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0]=old_values

In [63]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

array를 잘라도 array!

In [64]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

array 안의 array를 인덱스를 통하여 자료값을 통째로 바꿀수도 있음!

In [65]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [66]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

원소끼리 비교하여 각 원소의 boolean 값을 반환함.

In [70]:
data = np.random.randn(7,4) #randn 사용하려면 np.random 사용!

In [71]:
data

array([[-1.31379835,  0.39019375, -1.04277321,  0.35579989],
       [ 0.18092874, -0.8263824 , -2.79641982, -0.91963914],
       [ 0.71642638, -1.71816108,  0.64827024, -0.38247383],
       [ 0.03688772, -0.49421756, -0.69385474,  1.09460407],
       [ 0.30512204, -0.33027534, -0.14763105,  0.47708103],
       [-0.01924777,  0.30036275, -0.08947458, -0.53861091],
       [ 1.75517009, -0.24028943, -1.55528627, -1.5563173 ]])

In [72]:
data[names=='Bob']

array([[-1.31379835,  0.39019375, -1.04277321,  0.35579989],
       [ 0.03688772, -0.49421756, -0.69385474,  1.09460407]])

In [78]:
data[names=='Bob', 1]

array([ 0.39019375, -0.49421756])

boolean 값과 인덱스를 같이 사용해서 slicing할 수 있음!

In [79]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [87]:
data[~(names == 'Bob')] 

array([[ 0.18092874, -0.8263824 , -2.79641982, -0.91963914],
       [ 0.71642638, -1.71816108,  0.64827024, -0.38247383],
       [ 0.30512204, -0.33027534, -0.14763105,  0.47708103],
       [-0.01924777,  0.30036275, -0.08947458, -0.53861091],
       [ 1.75517009, -0.24028943, -1.55528627, -1.5563173 ]])

* &는 and, |는 or이다.

In [89]:
mask = (names =='Bob') | (names =='Will')

In [90]:
mask

array([ True, False,  True,  True,  True, False, False])

In [91]:
data[data<0]=0

In [92]:
data

array([[0.        , 0.39019375, 0.        , 0.35579989],
       [0.18092874, 0.        , 0.        , 0.        ],
       [0.71642638, 0.        , 0.64827024, 0.        ],
       [0.03688772, 0.        , 0.        , 1.09460407],
       [0.30512204, 0.        , 0.        , 0.47708103],
       [0.        , 0.30036275, 0.        , 0.        ],
       [1.75517009, 0.        , 0.        , 0.        ]])

In [93]:
arr = np.empty((8,4))

In [98]:
for i in range(8):
    arr[i] = i

In [99]:
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [100]:
arr[[3,2,6]]

array([[3, 3, 3, 3],
       [2, 2, 2, 2],
       [6, 6, 6, 6]])

In [101]:
arr = np.arange(32).reshape((8,4))

In [102]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [103]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

array의 [1,0], [5,3], [7,1], [2,2] 인덱스의 원소를 뽑아 array로 만들어줌

In [104]:
 arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] 

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

인덱스 1, 5, 7, 2 자리의 모든 데이터 안에서 인덱스 0, 3, 1, 2 자리의 값을 또 뽑아옴 

np.ix_ function => 2개의 1차원 array를 통해 slicing할 수 있도록 함.

In [105]:
 arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

np.dot => 행렬끼리의 곱 (원소끼리의 곱셈이 아닌 행렬곱)

In [106]:
 arr = np.arange(16).reshape((2, 2, 4))

In [107]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [108]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

x, y, z로 보고 y, x가 바뀌었다고 생각하자!

In [110]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

np.swapaxes : 축을 통해 array의 배열을 바꾸어줌.

In [113]:
arr=np.random.randn(7)*5

In [114]:
arr

array([ -0.20907709,  -3.4169042 ,  -6.9097204 ,   1.34971254,
       -11.31574326,  -1.17929974,   0.24093752])

In [115]:
np.modf(arr)

(array([-0.20907709, -0.4169042 , -0.9097204 ,  0.34971254, -0.31574326,
        -0.17929974,  0.24093752]),
 array([ -0.,  -3.,  -6.,   1., -11.,  -1.,   0.]))

np.modf(array) : 정수 부분과 소수 부분을 분리하여 첫 번째로 소수 부분의 자료값의 array, 두 번째로 정수 부분의 자료값의 array를 반환한다.

In [116]:
points = np.arange(-5, 5, 0.01)

In [117]:
xs, ys = np.meshgrid(points, points)

In [118]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [119]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [3]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [4]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [5]:
cond = np.array([True, False, True, True, False])

In [6]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

zip 함수 : 여러가지 list를 한꺼번에 slicing 할때 사용함

In [7]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

xarr, yarr, cond의 리스트 3개를 차례대로 접근하여 True이면 그 인덱스에 해당하는 xarr의 값을 가져오고, False이면 그 인덱스에 해당하는 yarr의 값을 가져온다.

저 코드와 같은 기능을 하는 메쏘드 => np.where(조건문, true일 때 지정할 값, false일 때 지정할 값)

In [10]:
arr = np.random.randn(4, 4)

In [11]:
arr

array([[ 0.06718161,  0.2031732 ,  0.35998778,  1.88095135],
       [-0.68775215,  1.63720108, -1.04108407, -0.6658856 ],
       [-1.39417254,  0.06655518, -1.64292568,  0.29126009],
       [ 1.57022544, -0.08687099, -0.02832727, -0.88361663]])

In [12]:
np.where(arr >0, 2, -2)

array([[ 2,  2,  2,  2],
       [-2,  2, -2, -2],
       [-2,  2, -2,  2],
       [ 2, -2, -2, -2]])

np.where 메쏘드는 조건문에 true에 해당하는지, false에 해당하는지를 모든 원소에 대해 판단하여 값을 return 한다.

In [13]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [15]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

cumsum(array, axis) => axis를 기준으로 누적합

In [16]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

cumprod(array, axis) => axis를 기준으로 누적곱

In [17]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [18]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

np.unique => 유일값을 return 해주는 메쏘드

In [20]:
 values = np.array([6, 0, 0, 3, 2, 5, 6])

In [21]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

np.in1d => 다른 array에 사용자가 준 1차원 array의 요소가 포함되어 있는가? 하나라도 있으면 True boolean 값을 리턴함

<대표적인 numpy.linalg 함수들>
dot : 행렬 곱
trace : 대각원소의 합을 계산
det : 행렬식 반환
qr : qr곱 반환
lsqtsq : 최소 제곱해 반환
solve : 선형시스템 Ax=b 계산
inv : 역행렬 반환

<random number generation>
rand : 균등분포로부터 샘플을 뽑아 반환
randint : 랜덤하게 정수 추출
randn : 평균이 0이고 표준편차가 1인 정규 분포로부터의 표본 추출
bionomial : 이항분포에서 표본 추출
normal : 정규분포에서 표본 추출